from crewai import Task

from agents import research_agent, blog_writer


research_task = Task(

    description="""
        You are given:

        Topic:
        {topic}

        Channel:
        {channel}

        Video Title:
        {video_title}

        Video URL:
        {video_url}

        Video Description:
        {video_description}

        Transcript:
        {transcript}

        Your objective is to completely understand the transcript.

        Do NOT summarize the transcript.

        Instead, analyze it like an expert researcher.

        Extract and organize:

        1. Video overview

        2. Learning objectives

        3. Important concepts

        4. Definitions

        5. Technical explanations

        6. Step-by-step workflows

        7. Practical examples

        8. Real-world use cases

        9. Analogies used by the speaker

        10. Code explanations (if present)

        11. Best practices

        12. Common mistakes or misconceptions

        13. Important terminology

        14. Key takeaways

        Preserve technical accuracy.

        Do not omit important information.

        Do not create information that is not present in the transcript.

        Your output will be consumed by another AI agent to write a professional blog.
        """,

    expected_output="""
    A detailed structured research report containing:

        - Video Overview
        - Learning Objectives
        - Important Concepts
        - Definitions
        - Technical Explanations
        - Workflows
        - Practical Examples
        - Real-world Use Cases
        - Speaker Analogies
        - Best Practices
        - Common Mistakes
        - Important Terminology
        - Key Takeaways

        The report must preserve all important technical knowledge from the transcript.

        """,

    agent=research_agent

)


blog_writing_task = Task(

    description="""
Using ONLY the research report generated by the Research Agent, write a complete technical blog.

The blog must be ready for publishing without any editing.

Requirements:

1. SEO-friendly title

2. Meta description

3. Engaging introduction

4. Table of Contents

5. Proper H2 and H3 headings

6. Explain concepts in logical order

7. Preserve all technical explanations

8. Preserve important examples

9. Add practical insights wherever appropriate

10. Use Markdown formatting

11. Include bullet points where useful

12. Include comparison tables if applicable

13. Add "Key Takeaways"

14. Add Frequently Asked Questions

15. End with a professional conclusion.

Do not invent facts.

Only use information available in the research report.
""",

    expected_output="""
    A publication-ready Markdown blog containing:

    - SEO Title
    - Meta Description
    - Introduction
    - Table of Contents
    - H2/H3 Sections
    - Bullet Lists
    - Comparison Tables (when applicable)
    - Practical Examples
    - Key Takeaways
    - FAQ Section
    - Conclusion

    The blog should require no further editing before publishing.
""",

    agent=blog_writer,

    context=[research_task],

    output_file="output/blog.md"

)